### ISSUE TITLE
4.06 compat release

### ISSUE THREAD

**Issue by tuncer** [whitequark/ulex#2]
Any predictions when opam will get a new release that's compatible with 4.06?

**Comment by whitequark** [comment]
Never, ulex is deprecated in favor of sedlex.

**Comment by whitequark** [comment]
Oh wait, nevermind, it isn't.

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/10854

**Comment by tuncer** [comment]
Thanks, closing since it's resolved.
